import React, { Component } from "react"

import {Avatar, Paper, Divider} from 'material-ui'

import NavBar from "../components/NavBar"

import '../style/SelectMerchant.css'
import {kStyleElevation, kStylePaper} from '../style/styleConstants'
import {WeiToDollars} from '../style/Formatter'


class SelectMerchant extends Component {

  render() {
    const merchants = [
      {
        name: "Devin the Merchant",
        offer: 90000000000000000,
        timeMin:7,
        timeMax:11,
      },
      {
        name: "Kevin's Big Shipping Company",
        offer: 75000000000000000,
        timeMin:15,
        timeMax:21,
      },
      {
        name: "Jeanette McMerchant",
        offer: 63000000000000000,
        timeMin:9,
        timeMax:14,
      },
      {
        name: "Amazon",
        offer: 68000000000000000,
        timeMin:10,
        timeMax:15,
      }
    ]
    return (
        <div>
          <NavBar title={"Select Merchant"} />
          <div className="page-container">
            <Paper elevation={kStyleElevation} style={kStylePaper}>
            <MerchantSelectHeader/>
            {
              merchants.map((m, i) => {
                return <MerchantSelect  key={i}
                                        name={m.name}
                                        offer={m.offer}
                                        days={[m.timeMin, m.timeMax]}
                                        index={i}/>
              })
            }
            </Paper>
          </div>
        </div>
      )
  }
}


class MerchantSelect extends Component {

  render() {

    const avatarStyle = (index) => {
      // Generated by locking in two colors and making new schemes
      const size = 60
      const colors = [
        "#317EAC", // main blue
        "#EDAE44", // main yellow
        "#4B7F52", // green
        "#7FD8BE", // aqua
        "#074F57", // turquoise

      ]
      return {"marginRight":10,
              "height":size,
              "width":size,
              "fontSize": 24,
              "backgroundColor":colors[index%colors.length]}
    }
    return (
          <div className = "merchant-select-merchant-box">
            <div className = "merchant-select-avatar">
              <Avatar style={avatarStyle(this.props.index)}>{this.props.name.charAt(0)}</Avatar>
            </div>
            <div className = "merchant-select-name">{this.props.name}</div>
            <div className = "merchant-select-price">${WeiToDollars(this.props.offer)}</div>
            <div className = "merchant-select-time">{this.props.days[0]} - {this.props.days[1]} days</div>
          </div>
      )
  }
}

class MerchantSelectHeader extends Component {

  render() {

    return (
        <div>
          <div className = "merchant-select-merchant-box merchant-header">
            <div className = "merchant-select-avatar merchant-header-text"/>
            <div className = "merchant-select-name merchant-header-text">Merchant<Divider/></div>
            <div className = "merchant-select-price merchant-header-text">Offer<Divider/></div>
            <div className = "merchant-select-time merchant-header-text">Shipping Time<Divider/></div>
          </div>
        </div>
      )
  }
}


export default SelectMerchant

